//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseManagementAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Pid { get; set; }
        public string Pname { get; set; }
        public int ProjManagerId { get; set; }
    
        public virtual EmployeeList EmployeeList { get; set; }
    }
}
